apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: devportal
  description: An example of a Backstage application.
  # Example for optional annotations
  annotations:
    github.com/project-slug: backstage/backstage
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: hellices@shinhan.com
  lifecycle: experimental

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: devportal
  description: The dev portal API
spec:
  type: openapi
  lifecycle: experimental
  owner: hellices@naver.com
  definition:
    $text: http://localhost:7007/api/catalog/entities