apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: shinhancard-develop-portal
  description: 신한카드 개발자 포탈 시스템. component(dev-portal), api(dev-portal-api), cd(dev-portal-flux-cd)
  links:
    - url: https://swa-backstage.shrnd.link
      title: dev portal production link
      icon: dashboard
spec:
  owner: shinhancard
  domain: shinhancard
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dev-portal
  links:
    - url: https://swa-backstage.shrnd.link
      title: dev portal production link
      icon: dashboard
    - url: https://swa-grafana.shrnd.link
      title: fluxcd monitoring
      icon: alarm
    - url: https://swa-jaeger.shrnd.link
      title: tracing tool
      icon: search
  tags:
    - typescript
    - backstage
    - shinhancard-dev-portal
  description: 신한카드 개발자 포탈입니다. 사용자 가이드는 DOCS -> user guide를 참고하시기 바랍니다.
  annotations:
    github.com/project-slug: shinhancard/dev-portal
    backstage.io/techdocs-ref: dir:.
    backstage.io/view-url: https://github.com/shinhancard/dev-portal/blob/main/catalog-info.yaml
    backstage.io/edit-url: https://github.com/shinhancard/dev-portal/edit/main/catalog-info.yaml
    backstage.io/source-location: url:https://github.com/shinhancard/dev-portal/
    github.com/team-slug: shinhancard/dev_portal_team
    backstage.io/code-coverage: enabled
spec:
  type: website
  owner: shinhancard
  lifecycle: experimental
  system: shinhancard-develop-portal

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: dev-portal
  description: shinhancard dev portal API
  links:
    - url: https://swa-backstage.shrnd.link
      title: dev portal production link
      icon: dashboard
spec:
  type: openapi
  lifecycle: experimental
  owner: shinhancard
  definition: |
    {
      "openapi": "3.0.1",
      "info": {
        "title": "A example document",
        "version": "1"
      },
      "host": "swa-backstage.shrnd.link",
      "paths": {
        "/catalog/refresh": {
          "post": {
            "responses": {
              "default": {
                "description": "Responses object not provided for this route"
              }
            }
          }
        },
        "/catalog/.well-known/backstage/permissions/metadata": {
          "get": {
            "responses": {
              "default": {
                "description": "Responses object not provided for this route"
              }
            }
          }
        },
        "/catalog/.well-known/backstage/permissions/apply-conditions": {
          "post": {
            "responses": {
              "default": {
                "description": "Responses object not provided for this route"
              }
            }
          }
        },
        "/catalog/entities": {
          "get": {
            "responses": {
              "default": {
                "description": "Responses object not provided for this route"
              }
            }
          }
        },
        "/catalog/entities/by-query": {
          "get": {
            "responses": {
              "default": {
                "description": "Responses object not provided for this route"
              }
            }
          }
        },
        "/catalog/entities/by-uid/{uid}": {
          "get": {
            "parameters": [
              {
                "name": "uid",
                "in": "path",
                "required": true,
                "schema": {
                  "type": "string"
                }
              }
            ],
            "responses": {
              "default": {
                "description": "Responses object not provided for this route"
              }
            }
          },
          "delete": {
            "parameters": [
              {
                "name": "uid",
                "in": "path",
                "required": true,
                "schema": {
                  "type": "string"
                }
              }
            ],
            "responses": {
              "default": {
                "description": "Responses object not provided for this route"
              }
            }
          }
        },
        "/catalog/entities/by-name/{kind}/{namespace}/{name}": {
          "get": {
            "parameters": [
              {
                "name": "kind",
                "in": "path",
                "required": true,
                "schema": {
                  "type": "string"
                }
              },
              {
                "name": "namespace",
                "in": "path",
                "required": true,
                "schema": {
                  "type": "string"
                }
              },
              {
                "name": "name",
                "in": "path",
                "required": true,
                "schema": {
                  "type": "string"
                }
              }
            ],
            "responses": {
              "default": {
                "description": "Responses object not provided for this route"
              }
            }
          }
        },
        "/catalog/entities/by-name/{kind}/{namespace}/{name}/ancestry": {
          "get": {
            "parameters": [
              {
                "name": "kind",
                "in": "path",
                "required": true,
                "schema": {
                  "type": "string"
                }
              },
              {
                "name": "namespace",
                "in": "path",
                "required": true,
                "schema": {
                  "type": "string"
                }
              },
              {
                "name": "name",
                "in": "path",
                "required": true,
                "schema": {
                  "type": "string"
                }
              }
            ],
            "responses": {
              "default": {
                "description": "Responses object not provided for this route"
              }
            }
          }
        },
        "/catalog/entities/by-refs": {
          "post": {
            "responses": {
              "default": {
                "description": "Responses object not provided for this route"
              }
            }
          }
        },
        "/catalog/entity-facets": {
          "get": {
            "responses": {
              "default": {
                "description": "Responses object not provided for this route"
              }
            }
          }
        },
        "/catalog/locations": {
          "post": {
            "responses": {
              "default": {
                "description": "Responses object not provided for this route"
              }
            }
          },
          "get": {
            "responses": {
              "default": {
                "description": "Responses object not provided for this route"
              }
            }
          }
        },
        "/catalog/locations/{id}": {
          "get": {
            "parameters": [
              {
                "name": "id",
                "in": "path",
                "required": true,
                "schema": {
                  "type": "string"
                }
              }
            ],
            "responses": {
              "default": {
                "description": "Responses object not provided for this route"
              }
            }
          },
          "delete": {
            "parameters": [
              {
                "name": "id",
                "in": "path",
                "required": true,
                "schema": {
                  "type": "string"
                }
              }
            ],
            "responses": {
              "default": {
                "description": "Responses object not provided for this route"
              }
            }
          }
        },
        "/catalog/analyze-location": {
          "post": {
            "responses": {
              "default": {
                "description": "Responses object not provided for this route"
              }
            }
          }
        },
        "/catalog/validate-entity": {
          "post": {
            "responses": {
              "default": {
                "description": "Responses object not provided for this route"
              }
            }
          }
        },
        "/auth/github/start": {
          "get": {
            "responses": {
              "default": {
                "description": "Responses object not provided for this route"
              }
            }
          }
        },
        "/auth/github/handler/frame": {
          "get": {
            "responses": {
              "default": {
                "description": "Responses object not provided for this route"
              }
            }
          },
          "post": {
            "responses": {
              "default": {
                "description": "Responses object not provided for this route"
              }
            }
          }
        },
        "/auth/github/logout": {
          "post": {
            "responses": {
              "default": {
                "description": "Responses object not provided for this route"
              }
            }
          }
        },
        "/auth/github/refresh": {
          "get": {
            "responses": {
              "default": {
                "description": "Responses object not provided for this route"
              }
            }
          },
          "post": {
            "responses": {
              "default": {
                "description": "Responses object not provided for this route"
              }
            }
          }
        },
        "/auth/.well-known/openid-configuration": {
          "get": {
            "responses": {
              "default": {
                "description": "Responses object not provided for this route"
              }
            }
          }
        },
        "/auth/.well-known/jwks.json": {
          "get": {
            "responses": {
              "default": {
                "description": "Responses object not provided for this route"
              }
            }
          }
        },
        "/auth/v1/token": {
          "get": {
            "responses": {
              "default": {
                "description": "Responses object not provided for this route"
              }
            }
          }
        },
        "/auth/v1/userinfo": {
          "get": {
            "responses": {
              "default": {
                "description": "Responses object not provided for this route"
              }
            }
          }
        },
        "/techdocs/metadata/techdocs/{namespace}/{kind}/{name}": {
          "get": {
            "parameters": [
              {
                "name": "namespace",
                "in": "path",
                "required": true,
                "schema": {
                  "type": "string"
                }
              },
              {
                "name": "kind",
                "in": "path",
                "required": true,
                "schema": {
                  "type": "string"
                }
              },
              {
                "name": "name",
                "in": "path",
                "required": true,
                "schema": {
                  "type": "string"
                }
              }
            ],
            "responses": {
              "default": {
                "description": "Responses object not provided for this route"
              }
            }
          }
        },
        "/techdocs/metadata/entity/{namespace}/{kind}/{name}": {
          "get": {
            "parameters": [
              {
                "name": "namespace",
                "in": "path",
                "required": true,
                "schema": {
                  "type": "string"
                }
              },
              {
                "name": "kind",
                "in": "path",
                "required": true,
                "schema": {
                  "type": "string"
                }
              },
              {
                "name": "name",
                "in": "path",
                "required": true,
                "schema": {
                  "type": "string"
                }
              }
            ],
            "responses": {
              "default": {
                "description": "Responses object not provided for this route"
              }
            }
          }
        },
        "/techdocs/sync/{namespace}/{kind}/{name}": {
          "get": {
            "parameters": [
              {
                "name": "namespace",
                "in": "path",
                "required": true,
                "schema": {
                  "type": "string"
                }
              },
              {
                "name": "kind",
                "in": "path",
                "required": true,
                "schema": {
                  "type": "string"
                }
              },
              {
                "name": "name",
                "in": "path",
                "required": true,
                "schema": {
                  "type": "string"
                }
              }
            ],
            "responses": {
              "default": {
                "description": "Responses object not provided for this route"
              }
            }
          }
        },
        "/search/query": {
          "get": {
            "responses": {
              "default": {
                "description": "Responses object not provided for this route"
              }
            }
          }
        },
        "/form-data/example/teams": {
          "get": {
            "responses": {
              "default": {
                "description": "Responses object not provided for this route"
              }
            }
          }
        },
        "/form-data/scaffolder/get/dependency/type": {
          "get": {
            "responses": {
              "default": {
                "description": "Responses object not provided for this route"
              }
            }
          }
        },
        "/form-data/scaffolder/get/dependency/name": {
          "get": {
            "responses": {
              "default": {
                "description": "Responses object not provided for this route"
              }
            }
          }
        },
        "/form-data/scaffolder/get/dependency/version": {
          "get": {
            "responses": {
              "default": {
                "description": "Responses object not provided for this route"
              }
            }
          }
        }
      }
    }
  system: shinhancard-develop-portal