apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: shinhancard-develop-portal
  description: 신한카드 개발자 포탈 시스템. component(dev-portal), api(dev-portal-api), cd(dev-portal-flux-cd)
  links:
    - url: https://swa-backstage.shrnd.link
      title: dev portal production link
      icon: dashboard
spec:
  owner: shinhancard
  domain: shinhancard
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dev-portal
  links:
    - url: https://swa-backstage.shrnd.link
      title: dev portal production link
      icon: dashboard
    - url: https://swa-grafana.shrnd.link
      title: fluxcd monitoring
      icon: alarm
    - url: https://swa-jaeger.shrnd.link
      title: tracing tool
      icon: search
  tags:
    - typescript
    - backstage
    - shinhancard-dev-portal
  description: 신한카드 개발자 포탈입니다. 사용자 가이드는 DOCS -> user guide를 참고하시기 바랍니다.
  annotations:
    github.com/project-slug: shinhancard/dev-portal
    backstage.io/techdocs-ref: dir:.
    backstage.io/view-url: https://github.com/shinhancard/dev-portal/blob/main/catalog-info.yaml
    backstage.io/edit-url: https://github.com/shinhancard/dev-portal/edit/main/catalog-info.yaml
    backstage.io/source-location: url:https://github.com/shinhancard/dev-portal/
    github.com/team-slug: shinhancard/dev_portal_team
    backstage.io/code-coverage: enabled
spec:
  type: website
  owner: shinhancard
  lifecycle: experimental
  system: shinhancard-develop-portal

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: dev-portal
  description: shinhancard dev portal API
  links:
    - url: https://swa-backstage.shrnd.link
      title: dev portal production link
      icon: dashboard
spec:
  type: openapi
  lifecycle: experimental
  owner: shinhancard
  definition:
    $text: https://swa-backstage.shrnd.link/api/openapispec/swagger.json
  system: shinhancard-develop-portal