name: "Request Help"
description:  잘 모르겠는 부분 또는 원인을 알 수 없음
title: "help request: "
label: ["help"]
body:
  - type: markdown
    attributes:
      value: |
        - Use Korean / English to communicate

  - type: textarea
    id: description
    attributes:
      label: Description
      description: 현재 이슈와 어떤 부분에서 도움을 받고 싶은지 기술
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: 이슈가 발생한 환경에 대한 상세 부분을 기술
      value: |
        - DevPortal version :
        - Backstage version (run `backstage-cli version`):
        - OS Type / Version :
        - React/ NodeJS version :
    validations:
      required: true