name: Build & Push Image to ECR
on:
    push:
      branches:
        - main
        - 'feature/**'
env:
  ECR_REPOSITORY: swa-ecr 
  EKS_CLUSTER: SHCW-AN2-RND-EKS-1
  CONTAINER_NAME: backstage
  AWS_REGION : ap-northeast-2 
  
permissions:
  id-token: write   
  contents: read

jobs:
  load_config:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
            role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
            role-session-name: SANDBOX-PUB-IAMR-GITHUB
            aws-region: ${{ env.AWS_REGION }}

      - run: aws sts get-caller-identity
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

  build_push:
    if: ${{ always() }}
    needs: [load_config]
    name: push image to ecr
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: docker/setup-buildx-action@v2
      - name: set current date as env variable
        run: echo "NOW=$(date +%s)" >> $GITHUB_ENV

      - name: install dependency packages 
        run: yarn install
        
      - name: Test unit
        run: yarn test
        
      - name: Build yarn dependencies
        run: yarn build:all 
        
      - name: Copy & Build to docker 
        env: 
          IMAGE_TAG: ${{ github.sha }} 
        run: DOCKER_BUILDKIT=1 yarn build-image --tag $IMAGE_TAG 
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
            role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
            role-session-name: SANDBOX-PUB-IAMR-GITHUB
            aws-region: ${{ env.AWS_REGION }}
            
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@main
        
      - name: push to ecr repo
        env:
          GITHUB_SHA: ${{github.sha}}
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: main-${{ github.sha }}-${{ env.NOW }}
        run: |
          echo $REGISTRY
          docker tag docker.io/library/$GITHUB_SHA $REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
