name: Deploy to EKS
on:
    workflow_run:
        workflows: [Build & Push Image to ECR]
        types:
          - completed

    push:
      branches:
        - main
        - 'feature/**'

env:
  ECR_REPOSITORY: swa-ecr 
  EKS_CLUSTER: SHCW-AN2-RND-EKS-1
  CONTAINER_NAME: backstage
  AWS_REGION : ap-northeast-2   
  IMAGE_TAG: ${{ github.sha }}
  
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: deploy image to eks
    runs-on: ubuntu-latest
    steps:
      - name: eks credential test
        run: aws eks update-kubeconfig --region ap-northeast-2 --name SHCW-AN2-RND-EKS-1

      - name: kubectl test
        run: kubectl get svc

      - name: EKS Service
        uses: koslibpro/helm-eks-action@master
        env: 
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          command: kubectl apply -f kubernetes/backstage.yaml
